- name: install and configure catalogue
  hosts: localhost
  become: yes
  tasks:
    - name: disable nodejs and enable nodejs 18
      ansible.builtin.shell: dnf module disable nodejs -y && dnf module enable nodejs:18 -y
    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: Create a user roboshop
      ansible.builtin.user:
        name: roboshop
      
        