- name: install my sql
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: "RoboShop@1"
  tasks:
  - name: disable mysql module
    ansible.builtin.shell: dnf module disable mysql -y

  - name: Install mysql server
    ansible.builtin.dnf:
      name: mysql-community-server
      state: present

  - name: enable and start mysql
    ansible.builtin.systemd_service:
      name: mysqld
      state: started
      enabled: true

  - name: set username and password for mysql
    ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ mysql_root_password }}
