- name: install and configure user
  hosts: user
  become: yes
  tasks:
    - name: disable nodejs and enable nodejs 18
      ansible.builtin.shell: dnf module disable nodejs -y && dnf module enable nodejs:18 -y
    
    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
   
    - name: Create a user roboshop
      ansible.builtin.user:
        name: roboshop
   
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory
   
    - name: Download Application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /tmp/user.zip
   
    - name: Unzip Application
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app 
        remote_src: yes
   
    - name: Install npm dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
   
    - name: setup symstemd for user service
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: Daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true
  
    - name: enable and start user
      ansible.builtin.systemd_service:
        name: user
        state: started
        enabled: true
  
    - name: Copy mongodb repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install mongodb client
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: present
    
    # load user schema when condition matches